// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: loadmonitor.proto

package loadmonitor_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	AgentId       int32                  `protobuf:"varint,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	DataName      string                 `protobuf:"bytes,3,opt,name=DataName,proto3" json:"DataName,omitempty"`
	Data          float64                `protobuf:"fixed64,4,opt,name=Data,proto3" json:"Data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_loadmonitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_loadmonitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_loadmonitor_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Metric) GetAgentId() int32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *Metric) GetDataName() string {
	if x != nil {
		return x.DataName
	}
	return ""
}

func (x *Metric) GetData() float64 {
	if x != nil {
		return x.Data
	}
	return 0
}

func (x *Metric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=Metrics,proto3" json:"Metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_loadmonitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_loadmonitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_loadmonitor_proto_rawDescGZIP(), []int{1}
}

func (x *Metrics) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricsAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           int32                  `protobuf:"varint,1,opt,name=Ack,proto3" json:"Ack,omitempty"`
	ScnFreq       int32                  `protobuf:"varint,2,opt,name=ScnFreq,proto3" json:"ScnFreq,omitempty"`
	TransMult     int32                  `protobuf:"varint,3,opt,name=TransMult,proto3" json:"TransMult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsAck) Reset() {
	*x = MetricsAck{}
	mi := &file_loadmonitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsAck) ProtoMessage() {}

func (x *MetricsAck) ProtoReflect() protoreflect.Message {
	mi := &file_loadmonitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsAck.ProtoReflect.Descriptor instead.
func (*MetricsAck) Descriptor() ([]byte, []int) {
	return file_loadmonitor_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsAck) GetAck() int32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *MetricsAck) GetScnFreq() int32 {
	if x != nil {
		return x.ScnFreq
	}
	return 0
}

func (x *MetricsAck) GetTransMult() int32 {
	if x != nil {
		return x.TransMult
	}
	return 0
}

var File_loadmonitor_proto protoreflect.FileDescriptor

var file_loadmonitor_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x6c, 0x6f, 0x61, 0x64, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6c, 0x6f, 0x61, 0x64, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x9c, 0x01, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0x38, 0x0a, 0x07, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c,
	0x6f, 0x61, 0x64, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x52, 0x07, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x56, 0x0a, 0x0a, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x41, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x63,
	0x6e, 0x46, 0x72, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x53, 0x63, 0x6e,
	0x46, 0x72, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x4d, 0x75, 0x6c,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x4d, 0x75,
	0x6c, 0x74, 0x32, 0x48, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f,
	0x72, 0x12, 0x39, 0x0a, 0x08, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x2e,
	0x6c, 0x6f, 0x61, 0x64, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x1a, 0x17, 0x2e, 0x6c, 0x6f, 0x61, 0x64, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f,
	0x72, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x41, 0x63, 0x6b, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x61, 0x69, 0x6e, 0x73,
	0x61, 0x72, 0x6b, 0x2f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x6c,
	0x6f, 0x61, 0x64, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_loadmonitor_proto_rawDescOnce sync.Once
	file_loadmonitor_proto_rawDescData []byte
)

func file_loadmonitor_proto_rawDescGZIP() []byte {
	file_loadmonitor_proto_rawDescOnce.Do(func() {
		file_loadmonitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loadmonitor_proto_rawDesc), len(file_loadmonitor_proto_rawDesc)))
	})
	return file_loadmonitor_proto_rawDescData
}

var file_loadmonitor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_loadmonitor_proto_goTypes = []any{
	(*Metric)(nil),                // 0: loadmonitor.Metric
	(*Metrics)(nil),               // 1: loadmonitor.Metrics
	(*MetricsAck)(nil),            // 2: loadmonitor.MetricsAck
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_loadmonitor_proto_depIdxs = []int32{
	3, // 0: loadmonitor.Metric.Timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: loadmonitor.Metrics.Metrics:type_name -> loadmonitor.Metric
	1, // 2: loadmonitor.LoadMonitor.LoadData:input_type -> loadmonitor.Metrics
	2, // 3: loadmonitor.LoadMonitor.LoadData:output_type -> loadmonitor.MetricsAck
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_loadmonitor_proto_init() }
func file_loadmonitor_proto_init() {
	if File_loadmonitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loadmonitor_proto_rawDesc), len(file_loadmonitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loadmonitor_proto_goTypes,
		DependencyIndexes: file_loadmonitor_proto_depIdxs,
		MessageInfos:      file_loadmonitor_proto_msgTypes,
	}.Build()
	File_loadmonitor_proto = out.File
	file_loadmonitor_proto_goTypes = nil
	file_loadmonitor_proto_depIdxs = nil
}
