version: "3.8"

services:
  influxdb:
    image: influxdb:2.6
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=vainsark
      - DOCKER_INFLUXDB_INIT_PASSWORD=vainsark
      - DOCKER_INFLUXDB_INIT_ORG=vainsark
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  influxdb_data:
  grafana_data:
