{
 "title": "Latency",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Dashboard",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; font-size: 36px;\"><b>Device: Raspberry_Pi_2  -  Agent: Latency<b></div>"
   }
  },
  {
   "title": "Monitoring Parameters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) =>\r\n       r._measurement == \"device_params\" and\r\n       r.deviceId      == \"Raspberry_Pi_2\" and\r\n       r.agentId       == \"Latency\"\r\n  )\r\n  |> filter(fn: (r) =>\r\n       r._field == \"ScnFreq\" or\r\n       r._field == \"TransMult\"\r\n  )\r\n  |> last()  // pick the latest point for each field series\r\n  |> pivot(\r\n       rowKey:       [\"_time\", \"deviceId\", \"agentId\"],\r\n       columnKey:    [\"_field\"],\r\n       valueColumn:  \"_value\"\r\n     )\r\n  |> keep(columns: [\"ScnFreq\", \"TransMult\"])\r\n  |> rename(columns: {ScnFreq: \"Scan Period [ms]\", TransMult: \"Transmission Multiplier\"})\r\n"
    }
   ]
  },
  {
   "title": "CPU Wake-Up Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"deviceId\"] == \"Raspberry_Pi_2\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Latency\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"CPU Latency\")\r\n  |> yield(name: \"cpu_laten\")"
    }
   ]
  },
  {
   "title": "Memory Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"deviceId\"] == \"Raspberry_Pi_2\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Latency\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Memory Latency\")\r\n  |> yield(name: \"memory_laten\")"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"deviceId\"] == \"Raspberry_Pi_2\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Latency\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"read wait\")\r\n  |> map(fn: (r) => ({ r with type: \"Read Wait\" }))\r\n  |> yield(name: \"storage read wait\")"
    },
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"deviceId\"] == \"Raspberry_Pi_2\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Latency\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"write wait\")\r\n  |> map(fn: (r) => ({ r with type: \"Write Wait\" }))\r\n  |> yield(name: \"storage write wait\")"
    }
   ]
  },
  {
   "title": "Sensor Read time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"deviceId\"] == \"Raspberry_Pi_2\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Latency\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Sensor Latency\")\r\n  |> map(fn: (r) => ({ r with type: \"Read Time\" }))\r\n  |> yield(name: \"sensoric read\")"
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"deviceId\"] == \"Raspberry_Pi_2\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Latency\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"NetInterLaten\")\r\n  |> map(fn: (r) => ({ r with type: \"Network Interface Latency\" }))\r\n  |> yield(name: \"utilization\")"
    }
   ]
  }
 ]
}