{
 "title": "LOAD",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Dashboard",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; font-size: 36px;\"><b>Device: Raspberry_Pi_2  -  Agent: Load<b></div>"
   }
  },
  {
   "title": "Monitoring Parameters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) =>\r\n       r._measurement == \"device_params\" and\r\n       r.deviceId      == \"Raspberry_Pi_2\" and\r\n       r.agentId       == \"Load\"\r\n  )\r\n  |> filter(fn: (r) =>\r\n       r._field == \"ScnFreq\" or\r\n       r._field == \"TransMult\"\r\n  )\r\n  |> last()  // pick the latest point for each field series\r\n  |> pivot(\r\n       rowKey:       [\"_time\", \"deviceId\", \"agentId\"],\r\n       columnKey:    [\"_field\"],\r\n       valueColumn:  \"_value\"\r\n     )\r\n  |> keep(columns: [\"ScnFreq\", \"TransMult\"])\r\n  |> rename(columns: {ScnFreq: \"Scan Period [ms]\", TransMult: \"Transmission Multiplier\"})\r\n"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"deviceId\"] == \"Raspberry_Pi_2\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Load\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"CPU Usage\")\r\n  |> yield(name: \"cpu_util\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"deviceId\"] == \"Raspberry_Pi_2\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Load\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Memory Usage\")\r\n  |> yield(name: \"memory_util\")"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"deviceId\"] == \"Raspberry_Pi_2\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Load\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Disk Usage\")\r\n  |> yield(name: \"disk_util\")"
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "  from(bucket: \"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"deviceId\"] == \"Raspberry_Pi_2\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Load\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"BytesWrite\" or r[\"type\"] == \"BytesRead\")\r\n  |> yield(name: \"Disk Read/Write\")\r\n"
    }
   ]
  },
  {
   "title": "Network Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "  from(bucket: \"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"deviceId\"] == \"Raspberry_Pi_2\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Load\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"BytesIn\" or r[\"type\"] == \"BytesOut\")\r\n  |> yield(name: \"network_util\")\r\n"
    }
   ]
  },
  {
   "title": "Sensoric load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "query": "  from(bucket: \"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"deviceId\"] == \"Raspberry_Pi_2\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Load\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Sensoric Read\" or r[\"type\"] == \"Sensoric Write\")\r\n  |> yield(name: \"Sensor Read/Write\")\r\n"
    }
   ]
  }
 ]
}